baseURL = 'https://mostlyinaccurate.com/'
languageCode = 'en-gb'
title = 'Mostly Inaccurate'
theme = "hugo-blog-awesome"
googleAnalytics = "G-YFZ8EN2G8W"

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

############################## English language ################################
[Languages.en-gb]
  languageName = "English"
  languageCode = "en-gb"
  contentDir = "content"
  weight = 1

  [Languages.en-gb.menu]
  [[Languages.en-gb.menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[Languages.en-gb.menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20

[Languages.en-gb.params]
  sitename = "Mostly Inaccurate"
  defaultColor = "dark" # set color mode: dark, light, auto
  # Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank,
  # the default value is set to 'auto'.
  # You can take a look at layouts/index.html for more information.
  description = "Succinct programming anecdotes from a pretend grown-up"
  mainSections = ['posts']
  toc = true # set to false to disable table of contents 'globally'

[Languages.en-gb.params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Mostly Inaccurate"
  name = "Chris"
  description = "Succinct programming anecdotes from a pretend grown-up"

# Allow to override `browserconfig.xml` params (configuration for windows embeded browsers)
[params.browserconfig]
  TileColor = "#2d89ef" # default windows 10 blue tile color

[[params.socialIcons]]
name = "github"
url = "https://github.com/cmpcdaly"
